# Generated by Django 4.0.1 on 2022-04-28 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('abbreviation', models.CharField(max_length=30)),
                ('stade', models.CharField(max_length=30)),
                ('president', models.CharField(max_length=30)),
                ('dateDeCreation', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Titres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligue', models.IntegerField(max_length=10)),
                ('superDZ', models.IntegerField(max_length=10)),
                ('cup', models.IntegerField(max_length=10)),
                ('caf', models.IntegerField(max_length=10)),
                ('conf', models.IntegerField(max_length=10)),
                ('SuperAF', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.AddField(
            model_name='equipe',
            name='titres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.titres'),
        ),
    ]
