# Generated by Django 4.0.1 on 2022-04-28 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_titres_superaf_alter_titres_caf_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Titres',
            new_name='Titre',
        ),
    ]
