# Generated by Django 4.0.1 on 2022-04-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_equipe_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='entraineur',
            field=models.CharField(default='', max_length=30),
        ),
    ]
