# Generated by Django 4.0.1 on 2022-05-15 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_equipe_entraineur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titre',
            name='SuperAF',
        ),
        migrations.RemoveField(
            model_name='titre',
            name='caf',
        ),
        migrations.RemoveField(
            model_name='titre',
            name='conf',
        ),
        migrations.RemoveField(
            model_name='titre',
            name='cup',
        ),
        migrations.AddField(
            model_name='titre',
            name='Supercoupe_afrique',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='titre',
            name='championnat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='titre',
            name='coupe_caf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='titre',
            name='coupe_dalgerie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='titre',
            name='coupe_des_coupe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='titres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.titre'),
        ),
        migrations.AlterField(
            model_name='titre',
            name='ligue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='titre',
            name='superDZ',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
