# Generated by Django 4.0.1 on 2022-05-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_titre_superaf_remove_titre_caf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='abbreviation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='entraineur',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='president',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='stade',
            field=models.CharField(max_length=50),
        ),
    ]
