# Generated by Django 4.0.1 on 2022-05-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_equipe_abbreviation_alter_equipe_entraineur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='dateDeCreation',
            field=models.DateField(),
        ),
    ]
